on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1 #TODO: Add Tests
        with:
          node-version: 12
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com 
